import type { Theme } from './types';

interface ThemeDefinition {
    name: Theme;
    displayName: string;
    colors: Record<string, string>;
}

export const themes: ThemeDefinition[] = [
    {
        name: 'vaporwave',
        displayName: 'Vaporwave',
        colors: {
            '--color-bg': '#1a1a2e',
            '--color-text': '#e0e0e0',
            '--color-text-muted': '#94a3b8',
            '--color-primary': '#ff00ff',
            '--color-secondary': '#00ffff',
            '--color-surface-1': 'rgba(0, 0, 0, 0.3)',
            '--color-surface-2': '#1e293b',
            '--color-surface-3': '#0f172a',
            '--color-border-primary': '#ff00ff',
            '--color-border-secondary': '#00ffff',
            '--color-border-muted': '#334155',
            '--color-priority-high': '#ef4444',
            '--color-priority-medium': '#facc15',
            '--color-priority-low': '#4ade80',
            '--color-selection-bg': '#ff00ff',
            '--color-selection-text': '#000',
        },
    },
    {
        name: 'arcade',
        displayName: 'Arcade Sunset',
        colors: {
            '--color-bg': '#2c1f3a',
            '--color-text': '#ffd700',
            '--color-text-muted': '#ffae42',
            '--color-primary': '#ff1493',
            '--color-secondary': '#ff6347',
            '--color-surface-1': 'rgba(0, 0, 0, 0.4)',
            '--color-surface-2': '#4a2e58',
            '--color-surface-3': '#1e1028',
            '--color-border-primary': '#ff1493',
            '--color-border-secondary': '#ff6347',
            '--color-border-muted': '#6a477a',
            '--color-priority-high': '#ff4500',
            '--color-priority-medium': '#ffd700',
            '--color-priority-low': '#adff2f',
            '--color-selection-bg': '#ffd700',
            '--color-selection-text': '#2c1f3a',
        },
    },
    {
        name: 'matrix',
        displayName: 'Matrix Green',
        colors: {
            '--color-bg': '#0d0d0d',
            '--color-text': '#00ff41',
            '--color-text-muted': '#008f11',
            '--color-primary': '#00ff41',
            '--color-secondary': '#008f11',
            '--color-surface-1': 'rgba(0, 20, 5, 0.5)',
            '--color-surface-2': '#002205',
            '--color-surface-3': '#001102',
            '--color-border-primary': '#00ff41',
            '--color-border-secondary': '#008f11',
            '--color-border-muted': '#004d0b',
            '--color-priority-high': '#cfff04',
            '--color-priority-medium': '#00ff41',
            '--color-priority-low': '#008f11',
            '--color-selection-bg': '#00ff41',
            '--color-selection-text': '#0d0d0d',
        },
    },
    {
        name: 'gameboy',
        displayName: 'Game Boy',
        colors: {
            '--color-bg': '#c4cfa1',
            '--color-text': '#0f380f',
            '--color-text-muted': '#52673d',
            '--color-primary': '#0f380f',
            '--color-secondary': '#52673d',
            '--color-surface-1': '#92a075',
            '--color-surface-2': '#818e6a',
            '--color-surface-3': '#a9b589',
            '--color-border-primary': '#0f380f',
            '--color-border-secondary': '#52673d',
            '--color-border-muted': '#52673d',
            '--color-priority-high': '#0f380f',
            '--color-priority-medium': '#52673d',
            '--color-priority-low': '#818e6a',
            '--color-selection-bg': '#0f380f',
            '--color-selection-text': '#c4cfa1',
        },
    },
    {
        name: 'accessible',
        displayName: 'High Contrast',
        colors: {
            '--color-bg': '#01041B',
            '--color-text': '#FFFFFF',
            '--color-text-muted': '#d0d0d0',
            '--color-primary': '#FFFF00',
            '--color-secondary': '#00FFFF',
            '--color-surface-1': '#101530',
            '--color-surface-2': '#182048',
            '--color-surface-3': '#080a20',
            '--color-border-primary': '#FFFF00',
            '--color-border-secondary': '#00FFFF',
            '--color-border-muted': '#334155',
            '--color-priority-high': '#FF4136',
            '--color-priority-medium': '#FFDC00',
            '--color-priority-low': '#7FDBFF',
            '--color-selection-bg': '#00FFFF',
            '--color-selection-text': '#01041B',
        },
    },
    {
        name: 'sakura',
        displayName: 'Sakura',
        colors: {
            '--color-bg': '#FFF5F5',
            '--color-text': '#5C3333',
            '--color-text-muted': '#8C6D6D',
            '--color-primary': '#FFB7C5',
            '--color-secondary': '#87CEEB',
            '--color-surface-1': '#FFE4E1',
            '--color-surface-2': '#FADADD',
            '--color-surface-3': '#FFF0F0',
            '--color-border-primary': '#FFB7C5',
            '--color-border-secondary': '#87CEEB',
            '--color-border-muted': '#D3B8B8',
            '--color-priority-high': '#E57373',
            '--color-priority-medium': '#FFD54F',
            '--color-priority-low': '#A5D6A7',
            '--color-selection-bg': '#FFB7C5',
            '--color-selection-text': '#5C3333',
        },
    },
    {
        name: '8bit',
        displayName: '8-Bit Classic',
        colors: {
            '--color-bg': '#222222',
            '--color-text': '#FFFFFF',
            '--color-text-muted': '#AAAAAA',
            '--color-primary': '#FF4136',
            '--color-secondary': '#0074D9',
            '--color-surface-1': '#333333',
            '--color-surface-2': '#444444',
            '--color-surface-3': '#111111',
            '--color-border-primary': '#FF4136',
            '--color-border-secondary': '#0074D9',
            '--color-border-muted': '#555555',
            '--color-priority-high': '#FF4136',
            '--color-priority-medium': '#FFDC00',
            '--color-priority-low': '#2ECC40',
            '--color-selection-bg': '#FFDC00',
            '--color-selection-text': '#222222',
        },
    },
    {
        name: 'light',
        displayName: 'Light Mode',
        colors: {
            '--color-bg': '#F5F5F5',
            '--color-text': '#111111',
            '--color-text-muted': '#666666',
            '--color-primary': '#005A9C',
            '--color-secondary': '#4A4A4A',
            '--color-surface-1': '#FFFFFF',
            '--color-surface-2': '#EAEAEA',
            '--color-surface-3': '#DDDDDD',
            '--color-border-primary': '#005A9C',
            '--color-border-secondary': '#AAAAAA',
            '--color-border-muted': '#CCCCCC',
            '--color-priority-high': '#D32F2F',
            '--color-priority-medium': '#FBC02D',
            '--color-priority-low': '#388E3C',
            '--color-selection-bg': '#005A9C',
            '--color-selection-text': '#FFFFFF',
        },
    },
];